accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    SignUpView,
    PersonalView,
)

app_name = 'accounts'

urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name='login'
    ),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('personal/', PersonalView.as_view(), name='personal'),
]

lex/urls.py
from django.contrib import admin
from django.urls import path, include
from lex import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('mails/', include('mails.urls', namespace='mails')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mails/urls.py
from django.urls import path
from .views import (
    SMTPAccountCreateView,
    SMTPAccountEditView,
    SMTPAccountDetailView,
    MessageDetailView,
    email_autocomplete,
)

app_name = 'mails'

urlpatterns = [
    path('create/', SMTPAccountCreateView.as_view(), name='create_smtp_acc'),
    path('edit/<int:pk>/', SMTPAccountEditView.as_view(), name='edit_smtp_acc'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='detail_message'),
    path('email_autocomplete', email_autocomplete, name='email_autocomplete'),
    path('<int:pk>/', SMTPAccountDetailView.as_view(), name='detail_smtp_acc'),
]

templates/personal/pages/personal_data.html
{% extends 'personal/base/base.html' %}
{% load static %}
{% block title %}
Личный кабинет
{% endblock title %}
{% block content %}
<div class="container-login100">
	<div class="wrap-login100">
		<div class="login100-pic js-tilt" data-tilt>
			{% if not request.user.customer.avatar %}
			<img src="{% static 'personal/images/img-01.png' %}" alt="IMG">
			{% else %}
			<img class="avatar-borders" src="{{ request.user.customer.avatar.url }}" alt="IMG">
			{% endif %}
			{% for acc in request.user.customer.smtpaccount_set.all %}
			<div class="text-left p-b-8" style="margin-top: 30px;">
				<span class="txt2 font-fix-bold" style="font-size: 15px;">
					Почта: {{ acc.default_from }}
				</span>
			</div>
			<div style="margin-top: 10px; display: flex; justify-content: space-between;">
				<button class="login100-form-btn font-fix-regular" onclick="location.href='{{ acc.get_detail_url }}';" style="width: 35%; display: inline-block; height: 30px; padding: 0px; text-transform: none;">
					Открыть
				</button>
				<button class="login100-form-btn font-fix-regular" onclick="location.href='{{ acc.get_edit_url }}';" style="width: 35%; display: inline-block; height: 30px; padding: 0px; text-transform: none;">
					Изменить
				</button>
			</div>
			{% endfor %}
			<div class="container-login100-form-btn" style="margin-top: 30px;">
				<button class="login100-form-btn font-fix-regular" onclick="location.href='{% url 'mails:create_smtp_acc'%}';">
					Подключить почту
				</button>
			</div>
		</div>
		<form class="login100-form validate-form" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<span class="login100-form-title font-fix-bold">
				Личный кабинет
			</span>
			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular">
					{{ form.name.label_tag }}
				</span>
			</div>
			<div class="wrap-input100" data-validate = "">
				{{ form.name }}
				<span class="focus-input100"></span>
			</div>
			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular alert-red">
					{{ form.errors.name }}
				</span>
			</div>

			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular">
					{{ form.facebook.label_tag }}
				</span>
			</div>
			<div class="wrap-input100" data-validate = "">
				{{ form.facebook }}
				<span class="focus-input100"></span>
			</div>
			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular alert-red">
					{{ form.errors.facebook }}
				</span>
			</div>

			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular">
					{{ form.twitter.label_tag }}
				</span>
			</div>
			<div class="wrap-input100" data-validate = "">
				{{ form.twitter }}
				<span class="focus-input100"></span>
			</div>
			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular alert-red">
					{{ form.errors.twitter }}
				</span>
			</div>

			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular">
					{{ form.instagram.label_tag }}
				</span>
			</div>
			<div class="wrap-input100" data-validate = "">
				{{ form.instagram }}
				<span class="focus-input100"></span>
			</div>
			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular alert-red">
					{{ form.errors.instagram }}
				</span>
			</div>

			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular">
					{{ form.avatar.label_tag }}
				</span>
			</div>
			<div class="wrap-input100 txt2 font-fix-regular" data-validate = "">
				{{ form.avatar }}
				<span class="focus-input100"></span>
			</div>
			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular alert-red">
					{{ form.errors.avatar }}
				</span>
			</div>

			<div class="container-login100-form-btn">
				<button class="login100-form-btn font-fix-regular">
					Сохранить
				</button>
			</div>

			<div class="text-center p-t-12">
				<a class="txt2 font-fix-regular" href="">
					Открыть диалоги
				</a>
			</div>

			<div class="text-center p-t-136">
				<a class="txt2 font-fix-regular" href="{% url 'accounts:logout' %}">
					Выйти из аккаунта
					<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
				</a>
			</div>
		</form>
	</div>
</div>
{% endblock %}

templates/personal/pages/smtp_account.html
{% extends 'personal/base/base.html' %}
{% load static %}
{% block title %}
Подключить почту
{% endblock title %}
{% block content %}
<div class="container-login100">
	<div class="wrap-login100" style="width: auto; padding: 177px 95px 33px 95px">
		<form class="login100-form validate-form" method="post" enctype="multipart/form-data" style="margin-left: auto; margin-right: auto;">
			{% csrf_token %}
			<span class="login100-form-title font-fix-bold">
				Подключение почты к системе
			</span>

			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular">
					{{ form.smtp.label_tag }}
				</span>
			</div>
			<div class="wrap-input100" data-validate = "">
				{{ form.smtp }}
				<span class="focus-input100"></span>
			</div>
			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular alert-red">
					{{ form.errors.smtp }}
				</span>
			</div>

      <div class="text-left p-b-8">
				<span class="txt2 font-fix-regular">
					{{ form.default_from.label_tag }}
				</span>
			</div>
			<div class="wrap-input100" data-validate = "">
				{{ form.default_from }}
				<span class="focus-input100"></span>
			</div>
			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular alert-red">
					{{ form.errors.default_from }}
				</span>
			</div>

      <div class="text-left p-b-8">
				<span class="txt2 font-fix-regular">
					{{ form.username.label_tag }}
				</span>
			</div>
			<div class="wrap-input100" data-validate = "">
				{{ form.username }}
				<span class="focus-input100"></span>
			</div>
			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular alert-red">
					{{ form.errors.username }}
				</span>
			</div>

      <div class="text-left p-b-8">
				<span class="txt2 font-fix-regular">
					{{ form.password.label_tag }}
				</span>
			</div>
			<div class="wrap-input100" data-validate = "">
				{{ form.password }}
				<span class="focus-input100"></span>
			</div>
			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular alert-red">
					{{ form.errors.password }}
				</span>
			</div>

			<div class="container-login100-form-btn">
				<button class="login100-form-btn font-fix-regular">
					Сохранить
				</button>
			</div>

			<div class="text-center p-t-136">
				<a class="txt2 font-fix-regular" href="{% url 'accounts:personal' %}">
					Вернуться в личный кабинет
					<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
				</a>
			</div>
		</form>
	</div>
</div>
{% endblock %}

templates/personal/pages/smtp_account_edit.html
{% extends 'personal/base/base.html' %}
{% load static %}
{% block title %}
Подключить почту
{% endblock title %}
{% block content %}
<div class="container-login100">
	<div class="wrap-login100" style="width: auto; padding: 177px 95px 33px 95px">
		<form class="login100-form validate-form" method="post" enctype="multipart/form-data" style="margin-left: auto; margin-right: auto;">
			{% csrf_token %}
			<span class="login100-form-title font-fix-bold">
				Изменение данных для {{ object.default_from }}
			</span>

      <div class="text-left p-b-8">
				<span class="txt2 font-fix-regular">
					Новый пароль
				</span>
			</div>
			<div class="wrap-input100" data-validate="">
				<input type="text" name="new_password" class="input100 font-fix-regular" maxlength="255" required="" id="id_new_password" autocomplete="off">
				<span class="focus-input100"></span>
			</div>
			{% comment %}
			<div class="text-left p-b-8">
				<span class="txt2 font-fix-regular">
				 ААААААааа
				</span>
			</div>
			{% endcomment %}

			<div class="container-login100-form-btn">
				<button class="login100-form-btn font-fix-regular">
					Сохранить
				</button>
			</div>

			<div class="text-center p-t-136">
				<a class="txt2 font-fix-regular" href="{% url 'accounts:personal' %}">
					Вернуться в личный кабинет
					<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
				</a>
			</div>
		</form>
	</div>
</div>
{% endblock %}